### PR TITLE
Added more polish translations

### PR DESCRIPTION
**Pull request by zneix**
Based on latest announcement in translation channel
Also fixed one minor typo in already existing translations

Original strings https://www.github.com/flex3r/DankChat/tree/master/app%2Fsrc%2Fmain%2Fres%2Fvalues%2Fstrings.xml

### CODE REVIEW

**Comment by zneix** [comment]
@heryin @izetpl @mm2pl could you please be so kind and have a look? Thanks!

**Review by IzeTPL — APPROVED** [review]
LGTM

**Review by Mm2PL — APPROVED** [review]

**Review by Heryin — APPROVED** [review]
LGTM

**Comment by flex3r** [comment]
👍

**Pull request merged**
