### PR TITLE
Format timeout duration

### PR DESCRIPTION
**Pull request by M4tthewDE**
First time contributing to any android project, so feel free to criticize.

### CODE REVIEW

**Comment by talneoran** [comment]
Maybe add weeks to this?

**Comment by flex3r** [comment]
Not sure, what does chatterino do? Maximum timeout should be 2 weeks right?

**Comment by M4tthewDE** [comment]
Chatterino does display weeks aswell, makes sense since maximum duration for a timeout is 2 weeks.

**Comment by talneoran** [comment]
Chatterino only supports weeks in some places, such as when you are the one performing the timeout, or in user timeout buttons, but not in the formatting of a CLEARCHAT message: 
`/timeout test 1w`
image
It's a small matter but I also think it makes sense with the max timeout.

**Review by flex3r — APPROVED** [review]
LGTM image

**Pull request merged**
