### PR TITLE
Added Spanish (from Spain) translation

### PR DESCRIPTION
**Pull request by cWve**
I don't know exactly what "Message scrollback length" means, so maybe the translation is a bit loose there.

### CODE REVIEW

**Comment by flex3r** [comment]
> I don't know exactly what "Message scrollback length" means, so maybe the translation is a bit loose there.

It defines how many messages you can see when scrolling up, so how big the message history should be

**Comment by cWve** [comment]
Okay, I think it's a bit easier to understand now.

**Comment by flex3r** [comment]
Seems good 👍 
I also just now added a few more strings for a tts setting. Not a high priority since it's a developer setting but if you want you can translate it as well

**Comment by cWve** [comment]
It's 2 strings right? Got it

**Review by flex3r — APPROVED** [review]
LGTM image
Feel free to ping me in #flex3rs if you want a contributor badge. There is also a discord so I can easily message translators if new strings have been added: https://discord.gg/vs7bhuw38M

**Pull request merged**
